

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    outputs:
      start_time: ${{ steps.start_time.outputs.start_time }}
      end_time: ${{ steps.end_time.outputs.end_time }}
      duration: ${{ steps.duration.outputs.duration }}

    steps:
    - uses: actions/checkout@v3
    - name: Set start time
      id: start_time
      run: echo "::set-output name=start_time::$(date +%s)"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Set end time and calculate duration
      id: end_time
      run: echo "::set-output name=end_time::$(date +%s)"

    - name: Calculate duration
      id: duration
      run: |
          start_time=${{ steps.start_time.outputs.start_time }}
          end_time=${{ steps.end_time.outputs.end_time }}
          duration=$((end_time - start_time))
          echo "::set-output name=duration::$duration"

    - name: Output scan time details
      run: |
          echo "Scan started at $(date -d @${{ steps.start_time.outputs.start_time }})"
          echo "Scan ended at $(date -d @${{ steps.end_time.outputs.end_time }})"
          echo "Total duration: ${{ steps.duration.outputs.duration }} seconds"
